name: Windows EXE Build

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'klaviyo_gui/**'
      - 'fetch_metrics.py'
      - 'scripts/build_windows.py'
      - '.github/workflows/windows-build.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up 64-bit Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r klaviyo_gui/requirements.txt
          pip install pyinstaller pywin32-ctypes

      - name: Build executables
        run: python scripts/build_windows.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: klaviyo-windows-exe
          path: |
            dist/KlaviyoSyncTool.exe
            dist/klaviyo_fetch_metrics.exe


